// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA36SqfS7z4x9izlo5JSJ7cYaydmYgkVo',
    appId: '1:489847768502:web:c52a713faa15bb8d7aed17',
    messagingSenderId: '489847768502',
    projectId: 'myportfolio-34aef',
    authDomain: 'myportfolio-34aef.firebaseapp.com',
    storageBucket: 'myportfolio-34aef.appspot.com',
    measurementId: 'G-0KS39Y0PVV',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYMaIAFaxi-iZW2hRYOhtbmvXRXGSQksE',
    appId: '1:489847768502:ios:b63c7011fd236fb57aed17',
    messagingSenderId: '489847768502',
    projectId: 'myportfolio-34aef',
    storageBucket: 'myportfolio-34aef.appspot.com',
    iosClientId: '489847768502-hs7mfucgv646h5fd4uo73d3bh6lnrhcs.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPortfolio',
  );
}
